version: '3.8'

services:
  thumbnails:
    container_name: thumbnails
    build: .
    env_file:
      - .env
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    volumes:
      - thumbnails:/data
    restart: unless-stopped

volumes:
  thumbnails:
